#!/bin/bash
# ================================================
#   Password Strength Analyzer - Bash Version
#   For educational use in cybersecurity course
# ================================================

# Colors
RED='\033[0;31m'
ORANGE='\033[0;33m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
DIM='\033[2m'
BOLD='\033[1m'
RESET='\033[0m'

# Report file
REPORT_FILE="password_report_$(date +%Y%m%d_%H%M%S).txt"
SESSION_COUNT=0

# ── Header ──────────────────────────────────────
print_header() {
  clear
  echo -e "${CYAN}"
  echo "  ╔══════════════════════════════════════════╗"
  echo "  ║     // Security Tool v1.0                ║"
  echo "  ║                                          ║"
  echo "  ║   PASSWORD  ANALYZER                     ║"
  echo "  ╚══════════════════════════════════════════╝"
  echo -e "${RESET}"
}

# ── Strength bar ────────────────────────────────
print_bar() {
  local score=$1 color=$2 bar=""
  for i in 1 2 3 4 5; do
    [ "$i" -le "$score" ] && bar+="${color}█${RESET}" || bar+="${DIM}░${RESET}"
  done
  echo -e "  Strength  : $bar"
}

# ── Crack time ───────────────────────────────────
crack_time() {
  python3 - <<EOF
charset = $1
length  = $2
if charset == 0 or length == 0:
    print("—")
else:
    s = (charset ** length) / 1e10 / 2
    if s < 1:           print("< 1 second")
    elif s < 60:        print(f"~{round(s)} seconds")
    elif s < 3600:      print(f"~{round(s/60)} minutes")
    elif s < 86400:     print(f"~{round(s/3600)} hours")
    elif s < 2592000:   print(f"~{round(s/86400)} days")
    elif s < 31536000:  print(f"~{round(s/2592000)} months")
    elif s < 3.15e9:    print(f"~{round(s/31536000)} years")
    elif s < 3.15e12:   print(f"~{s/3.15e9:.1f}K years")
    elif s < 3.15e15:   print(f"~{s/3.15e12:.1f}M years")
    else:               print("∞ (heat death of universe)")
EOF
}

# ── Entropy ──────────────────────────────────────
calc_entropy() {
  python3 -c "import math; c=$1; l=$2; print(f'{l*math.log2(c):.2f}' if c>0 and l>0 else '0.00')"
}

# ── SHA256 hash ──────────────────────────────────
hash_pwd() {
  echo -n "$1" | sha256sum | awk '{print $1}'
}

# ── Save report entry ────────────────────────────
save_report() {
  local label="$1" length="$2" charset="$3" entropy="$4"
  local crack="$5" unique="$6" hash="$7"
  local timestamp
  timestamp=$(date '+%Y-%m-%d %H:%M:%S')

  # Write header if file is new
  if [ ! -f "$REPORT_FILE" ]; then
    cat >> "$REPORT_FILE" << EOF
================================================
  PASSWORD ANALYSIS REPORT
  Generated by Password Analyzer v1.0
================================================

NOTE: Passwords are NOT stored. Only analysis
      results and SHA256 hashes are saved here.
================================================

EOF
  fi

  cat >> "$REPORT_FILE" << EOF
────────────────────────────────────────────────
  Entry     : #$SESSION_COUNT
  Timestamp : $timestamp
  SHA256    : $hash
  Strength  : $label
  Length    : $length chars
  Charset   : $charset symbols
  Entropy   : $entropy bits
  Unique    : $unique chars
  Crack est.: $crack
────────────────────────────────────────────────

EOF
}

# ── Analyze ──────────────────────────────────────
analyze() {
  local pwd="$1"
  local length=${#pwd}

  local has_upper=0 has_lower=0 has_digit=0 has_special=0 has_len8=0 has_len16=0
  [[ "$pwd" =~ [A-Z] ]]        && has_upper=1
  [[ "$pwd" =~ [a-z] ]]        && has_lower=1
  [[ "$pwd" =~ [0-9] ]]        && has_digit=1
  [[ "$pwd" =~ [^a-zA-Z0-9] ]] && has_special=1
  [ "$length" -ge 8 ]          && has_len8=1
  [ "$length" -ge 16 ]         && has_len16=1

  local charset=0
  [ $has_lower   -eq 1 ] && charset=$((charset+26))
  [ $has_upper   -eq 1 ] && charset=$((charset+26))
  [ $has_digit   -eq 1 ] && charset=$((charset+10))
  [ $has_special -eq 1 ] && charset=$((charset+32))
  [ $charset -eq 0 ] && [ $length -gt 0 ] && charset=26

  local score=0
  [ $has_len8    -eq 1 ] && score=$((score+1))
  [ $has_upper   -eq 1 ] && score=$((score+1))
  [ $has_lower   -eq 1 ] && score=$((score+1))
  ( [ $has_digit -eq 1 ] || [ $has_special -eq 1 ] ) && score=$((score+1))
  ( [ $has_len16 -eq 1 ] || ( [ $has_special -eq 1 ] && [ $length -ge 12 ] ) ) && score=$((score+1))

  local label color
  case $score in
    0) label="CRITICAL"; color=$RED    ;;
    1) label="WEAK"    ; color=$ORANGE ;;
    2) label="FAIR"    ; color=$YELLOW ;;
    3) label="GOOD"    ; color=$GREEN  ;;
    4) label="STRONG"  ; color=$GREEN  ;;
    5) label="FORTRESS"; color=$CYAN   ;;
  esac

  local unique entropy crack pwdhash
  unique=$(echo "$pwd" | grep -o . | sort -u | wc -l)
  entropy=$(calc_entropy "$charset" "$length")
  crack=$(crack_time "$charset" "$length")
  pwdhash=$(hash_pwd "$pwd")

  SESSION_COUNT=$((SESSION_COUNT+1))

  # ── Display ──
  print_header

  echo -e "  ${DIM}// Password (hidden for security)${RESET}"
  echo -e "  ${CYAN}$(printf '*%.0s' $(seq 1 $length))${RESET}  ${DIM}(${length} chars)${RESET}"
  echo ""

  print_bar "$score" "$color"
  echo -e "  Level     : ${color}${BOLD}$label${RESET}"
  echo -e "  Crack time: ${WHITE}$crack${RESET}"
  echo ""

  echo -e "  ${DIM}── Criteria Check ─────────────────────${RESET}"
  check_icon() { [ "$1" -eq 1 ] && echo -e "${GREEN}✓${RESET}" || echo -e "${DIM}○${RESET}"; }
  echo -e "  $(check_icon $has_len8)    Min. 8 chars          $(check_icon $has_upper)    Uppercase"
  echo -e "  $(check_icon $has_lower)    Lowercase             $(check_icon $has_digit)    Number (0-9)"
  echo -e "  $(check_icon $has_special)    Special char          $(check_icon $has_len16)    16+ chars"
  echo ""

  echo -e "  ${DIM}── Entropy & Stats ────────────────────${RESET}"
  printf "  %-20s ${CYAN}%s${RESET}\n"      "length"       "$length"
  printf "  %-20s ${CYAN}%s${RESET}\n"      "charset_size" "$charset"
  printf "  %-20s ${CYAN}%s bits${RESET}\n" "entropy_bits" "$entropy"
  printf "  %-20s ${CYAN}%s${RESET}\n"      "unique_chars" "$unique"
  echo ""

  echo -e "  ${DIM}── SHA256 Hash ─────────────────────────${RESET}"
  echo -e "  ${DIM}$pwdhash${RESET}"
  echo ""

  # ── Save report ──
  save_report "$label" "$length" "$charset" "$entropy" "$crack" "$unique" "$pwdhash"
  echo -e "  ${GREEN}✓ Report saved → ${WHITE}$REPORT_FILE${RESET}"
  echo ""
}

# ── Session summary ──────────────────────────────
print_summary() {
  if [ -f "$REPORT_FILE" ]; then
    echo -e "\n  ${CYAN}╔══════════════════════════════════════════╗"
    echo -e "  ║   Session complete: $SESSION_COUNT password(s) checked"
    echo -e "  ║   Report saved to: $REPORT_FILE"
    echo -e "  ╚══════════════════════════════════════════╝${RESET}\n"
  fi
}

# ── Main loop ────────────────────────────────────
print_header

while true; do
  echo -ne "  Enter password (or 'q' to quit): "
  read -rs pwd
  echo ""

  if [ "$pwd" = "q" ]; then
    print_summary
    exit 0
  fi

  [ -z "$pwd" ] && echo -e "  ${RED}No password entered.${RESET}\n" && continue

  analyze "$pwd"

  echo -ne "  ${DIM}Press Enter to check another...${RESET}"
  read -r
done
